(function(){
"use strict";
const THEME="lecho-theme";
function applyTheme(mode){const dark=mode==="dark";document.documentElement.classList.toggle("dark",dark);document.querySelectorAll("[data-theme]").forEach(b=>{b.textContent=dark?"☀️ Clair":"🌙 Sombre";b.setAttribute("aria-label",dark?"Passer au mode clair":"Passer au mode sombre")});}
function initTheme(){applyTheme(localStorage.getItem(THEME)==="dark"?"dark":"light");document.addEventListener("click",e=>{const b=e.target.closest("[data-theme]");if(!b)return;const next=document.documentElement.classList.contains("dark")?"light":"dark";localStorage.setItem(THEME,next);applyTheme(next)})}
const months=["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"];
function dateRP(){const d=new Date();return d.getDate()+" "+months[d.getMonth()]+" 1474"}
function leaves(){const box=document.querySelector("#leaves");if(!box||matchMedia("(prefers-reduced-motion: reduce)").matches)return;for(let i=0;i<16;i++){let x=document.createElement("span");x.className="leaf";x.textContent=["🍂","🍁","🍃"][i%3];x.style.left=Math.random()*100+"vw";x.style.animationDuration=7+Math.random()*8+"s";x.style.animationDelay=-(Math.random()*12)+"s";x.style.fontSize=12+Math.random()*15+"px";box.appendChild(x)}}
async function articles(){try{return await (await fetch("articles.json")).json()}catch(e){return []}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function render(){document.querySelectorAll("[data-rp-date]").forEach(e=>e.textContent=dateRP());leaves();const list=await articles();const box=document.querySelector("#article-list");if(box){const paint=a=>box.innerHTML=a.map(x=>`<article class="card"><div class="label">${esc(x.category)} · ${esc(x.kingdom)}</div><div class="meta">${esc(x.date_display)} · ${esc(x.author)}</div><h3>${esc(x.title)}</h3><p>${esc(x.excerpt)}</p><a href="article.html?id=${encodeURIComponent(x.id)}">Lire l’article →</a></article>`).join("");paint(list);const input=document.querySelector("#search");if(input)input.addEventListener("input",()=>{const q=input.value.toLowerCase();paint(list.filter(x=>(x.title+" "+x.author+" "+x.kingdom+" "+x.category+" "+x.excerpt).toLowerCase().includes(q)))})}
const view=document.querySelector("#article-view");if(view){const id=new URLSearchParams(location.search).get("id");const a=list.find(x=>x.id===id)||list[0];if(a)view.innerHTML=`<article class="paper article"><div class="label">${esc(a.category)} · ${esc(a.kingdom)}</div><div class="meta">${esc(a.date_display)} · Par ${esc(a.author)}</div><h2>${esc(a.title)}</h2><p class="chapo">${esc(a.excerpt)}</p><img class="article-image" src="${esc(a.image)}" alt="${esc(a.title)}"><div>${a.sections.map(s=>(s.title?`<h3>${esc(s.title)}</h3>`:"")+s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join("")).join("")}</div><div class="signature"><em>${esc(a.author)}</em></div></article>`}}
}
document.addEventListener("DOMContentLoaded",()=>{initTheme();render()});
})();