(function(){
"use strict";
const KEY="lecho-theme";
const months=["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"];
function applyTheme(dark){document.documentElement.classList.toggle("dark",dark);document.body.classList.toggle("dark",dark);document.querySelectorAll("[data-theme]").forEach(b=>{b.textContent=dark?"☀️ Clair":"🌙 Sombre";b.setAttribute("aria-pressed",dark?"true":"false")})}
function theme(){applyTheme(localStorage.getItem(KEY)==="dark");document.addEventListener("click",e=>{const b=e.target.closest("[data-theme]");if(!b)return;const d=!document.documentElement.classList.contains("dark");localStorage.setItem(KEY,d?"dark":"light");applyTheme(d)})}
function rpDate(){const d=new Date();return d.getDate()+" "+months[d.getMonth()]+" 1474"}
function leaves(){const box=document.getElementById("leaves");if(!box||matchMedia("(prefers-reduced-motion: reduce)").matches)return;for(let i=0;i<18;i++){const x=document.createElement("span");x.className="leaf";x.textContent=["🍂","🍁","🍃"][i%3];x.style.left=Math.random()*100+"vw";x.style.animationDuration=7+Math.random()*9+"s";x.style.animationDelay=-(Math.random()*12)+"s";x.style.fontSize=12+Math.random()*16+"px";box.appendChild(x)}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function getArticles(){try{return await (await fetch("articles.json",{cache:"no-store"})).json()}catch(e){return[]}}
function card(a){return `<article class="card"><div class="label">${esc(a.category||"Article")} · ${esc(a.kingdom||"")}</div><div class="meta">${esc(a.date_display||"")} · ${esc(a.author||"")}</div><h3>${esc(a.title)}</h3><p>${esc(a.excerpt||"")}</p><a href="article.html?id=${encodeURIComponent(a.id)}">Lire l’article →</a></article>`}
async function render(){document.querySelectorAll("[data-rp-date]").forEach(e=>e.textContent=rpDate());leaves();const list=await getArticles();const box=document.getElementById("article-list");if(box){const paint=a=>box.innerHTML=a.map(card).join("");paint(list);const q=document.getElementById("search");if(q)q.addEventListener("input",()=>{const s=q.value.toLowerCase();paint(list.filter(a=>(a.title+" "+a.author+" "+a.kingdom+" "+a.category+" "+a.excerpt).toLowerCase().includes(s)))})}const view=document.getElementById("article-view");if(view){const id=new URLSearchParams(location.search).get("id");const a=list.find(x=>x.id===id)||list[0];if(a)view.innerHTML=`<article class="paper article"><div class="label">${esc(a.category||"Article")} · ${esc(a.kingdom||"")}</div><div class="meta">${esc(a.date_display||"")} · Par ${esc(a.author||"")}</div><h2>${esc(a.title)}</h2><p class="chapo">${esc(a.excerpt||"")}</p>${a.image?`<img class="article-image" src="${esc(a.image)}" alt="${esc(a.title)}">`:""}${(a.sections||[]).map(s=>(s.title?`<h3>${esc(s.title)}</h3>`:"")+(s.paragraphs||[]).map(p=>`<p>${esc(p)}</p>`).join("")).join("")}<div class="signature"><em>${esc(a.author||"")}</em></div></article>`}}
document.addEventListener("DOMContentLoaded",()=>{theme();render()});
})();